project:
  type: website
  output-dir: _site

website:
  title: "Projet TDAH Tunisie"
  navbar:
    background: primary
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Rapport Principal"
        href: rapport_principal.qmd
      - text: "PrÃ©sentation"
        href: presentation.qmd
    right:
      - icon: github
        href: https://github.com/asmabelkahla/Etude-Analytics-du-TDAH-chez-les-Enfants-Tunisiens
  sidebar:
    style: "floating"
    contents:
      - text: "ğŸ  Accueil"
        href: index.qmd
      - text: "---"
      - section: "ğŸ“š Documents Principaux"
        contents:
          - text: "ğŸ“Š Rapport Principal"
            href: rapport_principal.qmd
          - text: "ğŸ¤ PrÃ©sentation"
            href: presentation.qmd
      - text: "---"
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    embed-resources: false
    html-math-method: katex

execute:
  echo: false
  warning: false
  message: false
